apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ .Values.appName }}
spec:
  rules:
  - host: {{ .Values.appUrl }}
    http:
      paths: 
        - path: /
          pathType: Prefix
          backend:
            service:
              name: {{ .Values.appName }}
              port:
                number: {{ .Values.servicePort }}