appName: app
containerPort: 8000
servicePort: 80
serviceType: ClusterIP
appImage: mrbochanov/app
appVersion: latest
appReplicas: 2
appUrl: farfordev.ru
containerEnvVars:
  - key: ENVIRONMENT
    value: "dev"
  - key: ENVIRONMENT_FROM_SECRET
    value: "secretdev"  